language: node_js
sudo: false
dist: trusty

node_js:
  - node

before_script:
  - yarn install

script:
  - gulp lint
  - gulp test

before_deploy:
  - gulp build:prod
  - sh ci/before_deploy.sh

deploy:
  provider: s3
  access_key_id: arst
  secret_access_key:
    secure: arst
  bucket: js-apps-builds-nemopay
  region: eu-west-1
  local-dir: dist
  upload-dir: seat-manager
  acl: public_read
  skip_cleanup: true
  on:
    branch: master
